const fs = require('fs');
let content = fs.readFileSync('frontend/src/screens/PassesScreen.tsx', 'utf8');

// I need to change what happens when clicking Subscribe.
// Wait, the user's PassesScreen is generated by the colleague, I should check how it works.
