import { StyleSheet, Platform } from 'react-native';
import { tokens } from '../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.paleMapBackground,
  },
  safeArea: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  activeReservationContainer: {
    zIndex: 100,
  },
  activeReservationPanel: {
    padding: 20,
    backgroundColor: tokens.colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: tokens.colors.primaryText,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  headerContainer: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 40 : 16,
    left: 16,
    right: 16,
  },
  headerPanel: {
    padding: 16,
    paddingBottom: 12,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  wordmark: {
    flexShrink: 0,
    fontFamily: tokens.typography.heading,
    fontSize: 20,
    fontWeight: '800',
    color: tokens.colors.primaryText,
    letterSpacing: -0.5,
  },
  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 153, 103, 0.10)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: tokens.radii.pill,
  },
  locationText: {
    fontFamily: tokens.typography.body,
    fontSize: 12,
    fontWeight: '600',
    color: tokens.colors.availabilityGreen,
    marginLeft: 4,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  passesShortcut: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.primaryText,
    marginRight: 12,
  },
  avatar: {
    flexShrink: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.colors.emerald,
  },
  reviewPrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  standingNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  standingNoticeTitle: {
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 13,
  },
  standingNoticeText: {
    fontFamily: tokens.typography.body,
    fontSize: 11,
    color: tokens.colors.secondaryText,
    marginTop: 2,
  },
  reviewPromptIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewPromptTextWrapper: {
    flex: 1,
    marginLeft: 10,
    marginRight: 8,
  },
  reviewPromptTitle: {
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 13,
    color: tokens.colors.primaryText,
  },
  reviewPromptSubtitle: {
    fontFamily: tokens.typography.body,
    fontSize: 11,
    color: tokens.colors.secondaryText,
    marginTop: 2,
  },
  reviewPromptAction: {
    backgroundColor: tokens.colors.emerald,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  reviewPromptActionText: {
    color: tokens.colors.white,
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 12,
  },
  reviewPromptClose: {
    padding: 4,
    marginLeft: 4,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.white,
    borderRadius: tokens.radii.inputControl,
    paddingHorizontal: 12,
    height: 48,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  searchContainerFocused: {
    borderColor: tokens.colors.emerald,
    backgroundColor: tokens.colors.emeraldWash,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontFamily: tokens.typography.body,
    fontSize: 16,
    color: tokens.colors.primaryText,
  },
  suggestionsContainer: {
    backgroundColor: tokens.colors.white,
    borderRadius: tokens.radii.inputControl,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
  },
  suggestionTextContainer: {
    marginLeft: 10,
    flex: 1,
    minWidth: 0,
  },
  suggestionName: {
    fontFamily: tokens.typography.bodyMedium,
    fontSize: 14,
    color: tokens.colors.primaryText,
  },
  suggestionSubtitle: {
    fontFamily: tokens.typography.body,
    fontSize: 12,
    color: tokens.colors.secondaryText,
    marginTop: 2,
  },
  noResultsRow: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  noResultsText: {
    fontFamily: tokens.typography.body,
    fontSize: 13,
    color: tokens.colors.secondaryText,
  },
  filtersScroll: {
    flexDirection: 'row',
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: tokens.radii.pill,
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: tokens.colors.emerald,
    borderColor: tokens.colors.emerald,
  },
  filterText: {
    fontFamily: tokens.typography.body,
    fontSize: 13,
    fontWeight: '500',
    color: tokens.colors.secondaryText,
  },
  filterTextActive: {
    color: tokens.colors.white,
  },
  mapControls: {
    position: 'absolute',
    right: 16,
    bottom: 40,
    alignItems: 'center',
  },
  controlGroup: {
    marginBottom: 12,
  },
  controlSingle: {
  },
  controlButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    width: '100%',
  },
  bookingSheetWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 200,
  },
  bookingSheet: {
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 24,
    paddingTop: 12,
  },
  dragHandleContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  spotName: {
    fontFamily: tokens.typography.heading,
    fontSize: 20,
    fontWeight: '700',
    color: tokens.colors.primaryText,
    marginBottom: 4,
  },
  spotDetails: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    color: tokens.colors.secondaryText,
    marginBottom: 4,
  },
  availableText: {
    fontFamily: tokens.typography.body,
    fontSize: 15,
    fontWeight: '700',
    color: tokens.colors.availabilityGreen,
  },
  closeButton: {
    marginBottom: 8,
  },
  spotPrice: {
    fontFamily: tokens.typography.heading,
    fontSize: 20,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  },
  perHour: {
    fontSize: 14,
    fontWeight: '500',
    color: tokens.colors.secondaryText,
  },
  timeControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  timeControlBox: {
    flex: 1,
    backgroundColor: tokens.colors.white,
    padding: 12,
    borderRadius: tokens.radii.inputControl,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  timeLabel: {
    fontFamily: tokens.typography.body,
    fontSize: 12,
    color: tokens.colors.secondaryText,
    marginBottom: 4,
  },
  timeValue: {
    fontFamily: tokens.typography.body,
    fontSize: 15,
    fontWeight: '600',
    color: tokens.colors.primaryText,
  },
  costSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  costLabel: {
    fontFamily: tokens.typography.body,
    fontSize: 16,
    fontWeight: '500',
    color: tokens.colors.primaryText,
  },
  costValue: {
    fontFamily: tokens.typography.heading,
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  },
  depositText: {
    fontFamily: tokens.typography.body,
    fontSize: 12,
    color: tokens.colors.warningAmber,
    marginBottom: 20,
  },
  reserveButton: {
    backgroundColor: tokens.colors.emerald,
    paddingVertical: 16,
    borderRadius: tokens.radii.inputControl,
    alignItems: 'center',
  },
  reserveButtonText: {
    fontFamily: tokens.typography.heading,
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.white,
  },
  municipalWarning: {
    backgroundColor: 'rgba(15, 118, 110, 0.1)',
    padding: 16,
    borderRadius: tokens.radii.inputControl,
    alignItems: 'center',
  },
  municipalWarningText: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.municipalTeal,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    padding: 24,
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalSection: {
    marginBottom: 24,
  },
  sectionLabel: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.secondaryText,
    marginBottom: 12,
  },
  vehicleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2F5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  vehicleChipSelected: {
    backgroundColor: tokens.colors.emerald,
  },
  vehicleChipText: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    color: tokens.colors.primaryText,
  },
  vehicleChipTextSelected: {
    color: tokens.colors.white,
    fontWeight: '600',
  },
  plateInput: {
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: tokens.radii.inputControl,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontFamily: tokens.typography.body,
    fontSize: 16,
    color: tokens.colors.primaryText,
  },
  saveVehicleBtn: {
    backgroundColor: tokens.colors.emerald,
    borderRadius: tokens.radii.inputControl,
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveVehicleBtnText: {
    color: tokens.colors.white,
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 15,
  },
  timeScroll: {
    flexDirection: 'row',
  },
  timeChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: tokens.radii.pill,
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 8,
  },
  timeChipActive: {
    backgroundColor: tokens.colors.emerald,
    borderColor: tokens.colors.emerald,
  },
  timeText: {
    fontFamily: tokens.typography.body,
    fontSize: 15,
    fontWeight: '600',
    color: tokens.colors.primaryText,
  },
  sliderLabel: {
    fontFamily: tokens.typography.body,
    fontSize: 12,
    color: tokens.colors.secondaryText,
  },
  arrivalSliderValue: {
    fontFamily: tokens.typography.heading,
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  },
  timeSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: tokens.radii.inputControl,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  timeSelectText: {
    fontFamily: tokens.typography.body,
    fontSize: 16,
    fontWeight: '600',
    color: tokens.colors.primaryText,
  },
  departureText: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.availabilityGreen,
  },
  durationControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: tokens.radii.inputControl,
    padding: 8,
  },
  durBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: tokens.colors.paleMapBackground,
    borderRadius: 8,
  },
  durationValue: {
    fontFamily: tokens.typography.heading,
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  },
  receiptContainer: {
    backgroundColor: tokens.colors.paleMapBackground,
    padding: 16,
    borderRadius: tokens.radii.inputControl,
    marginBottom: 24,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  receiptLabel: {
    flex: 1,
    marginRight: 16,
    fontFamily: tokens.typography.body,
    fontSize: 14,
    color: tokens.colors.secondaryText,
  },
  receiptValue: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.primaryText,
  },
  discountValue: {
    fontFamily: tokens.typography.body,
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.availabilityGreen,
  },
  waivedValue: {
    color: tokens.colors.availabilityGreen,
  },
  passAppliedText: {
    fontFamily: tokens.typography.body,
    fontSize: 11,
    color: tokens.colors.availabilityGreen,
    marginTop: 2,
    marginBottom: 4,
  },
  receiptDivider: {
    height: 1,
    backgroundColor: '#D1D5DB',
    marginVertical: 12,
  },
  receiptTotalLabel: {
    fontFamily: tokens.typography.heading,
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  },
  receiptTotalValue: {
    fontFamily: tokens.typography.heading,
    fontSize: 18,
    fontWeight: '700',
    color: tokens.colors.primaryText,
  }
});
