import { StyleSheet } from 'react-native';
import { tokens } from '../theme/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.colors.paleMapBackground,
  },
  scrollContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 36,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: tokens.radii.upperSheet,
    overflow: 'hidden',
    padding: 18,
    marginBottom: 20,
    ...tokens.shadows.soft,
  },
  headerSheen: {
    position: 'absolute',
    right: -50,
    top: -70,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  screenTitle: {
    color: tokens.colors.white,
    fontFamily: tokens.typography.headingBold,
    fontSize: 32,
    lineHeight: 38,
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontFamily: tokens.typography.body,
    fontSize: 14,
    marginTop: 4,
  },
  headerIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  summaryCard: {
    padding: 18,
    marginBottom: 26,
  },
  summaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  summaryIcon: {
    alignItems: 'center',
    backgroundColor: tokens.colors.emeraldTint,
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  summaryText: {
    flex: 1,
    marginLeft: 12,
  },
  summaryTitle: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 15,
  },
  summaryCaption: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 12,
    marginTop: 3,
  },
  metricsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 20,
  },
  metric: {
    flex: 1,
  },
  metricValue: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.headingBold,
    fontSize: 20,
  },
  metricLabel: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 12,
    marginTop: 2,
  },
  metricDivider: {
    backgroundColor: '#DDE3E7',
    height: 32,
    width: 1,
  },
  sectionHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.headingMedium,
    fontSize: 20,
  },
  bookingCount: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 12,
  },
  bookingList: {
    gap: 12,
  },
  bookingCard: {
    padding: 16,
  },
  cardTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  locationIcon: {
    alignItems: 'center',
    backgroundColor: tokens.colors.emeraldTint,
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  locationInfo: {
    flex: 1,
    marginLeft: 11,
    marginRight: 8,
  },
  locationName: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 15,
  },
  address: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 11,
    marginTop: 4,
  },
  statusBadge: {
    alignItems: 'center',
    borderRadius: tokens.radii.pill,
    flexDirection: 'row',
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  statusText: {
    fontFamily: tokens.typography.bodyMedium,
    fontSize: 11,
    marginLeft: 4,
  },
  detailsRow: {
    borderBottomColor: '#E4E9EC',
    borderBottomWidth: 1,
    borderTopColor: '#E4E9EC',
    borderTopWidth: 1,
    flexDirection: 'row',
    marginTop: 16,
    paddingVertical: 12,
  },
  detailItem: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  detailText: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.body,
    fontSize: 12,
    marginLeft: 6,
  },
  cardFooter: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
  },
  footerLabel: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.bodyMedium,
    fontSize: 12,
  },
  bookingId: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 11,
    marginTop: 4,
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  price: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.headingBold,
    fontSize: 17,
  },
  priceLabel: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 10,
    marginTop: 1,
  },
  rateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FDE68A',
    backgroundColor: '#FFFBEB',
  },
  rateButtonText: {
    marginLeft: 6,
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.bodySemiBold,
    fontSize: 13,
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  emptyIcon: {
    alignItems: 'center',
    backgroundColor: '#E1E7EA',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  emptyTitle: {
    color: tokens.colors.primaryText,
    fontFamily: tokens.typography.headingMedium,
    fontSize: 17,
    marginTop: 14,
  },
  emptyText: {
    color: tokens.colors.secondaryText,
    fontFamily: tokens.typography.body,
    fontSize: 13,
    marginTop: 5,
  },
});
