import { StyleSheet } from 'react-native';
import { tokens } from '../theme/tokens';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: tokens.colors.paleMapBackground },
  content: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 18, paddingBottom: 36 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  title: { color: tokens.colors.primaryText, fontFamily: tokens.typography.headingBold, fontSize: 32, lineHeight: 38 },
  subtitle: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 14, marginTop: 4 },
  headerIcon: { alignItems: 'center', backgroundColor: tokens.colors.white, borderRadius: 22, height: 44, justifyContent: 'center', width: 44, ...tokens.shadows.soft },
  hero: { backgroundColor: tokens.colors.emeraldDeep, padding: 20, marginBottom: 18 },
  heroIcon: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 14, height: 44, justifyContent: 'center', width: 44 },
  heroTitle: { color: tokens.colors.white, fontFamily: tokens.typography.headingBold, fontSize: 22, marginTop: 16 },
  heroText: { color: 'rgba(255,255,255,0.78)', fontFamily: tokens.typography.body, fontSize: 13, lineHeight: 20, marginTop: 7 },
  heroPerks: { flexDirection: 'row', gap: 18, marginTop: 18 },
  heroPerk: { alignItems: 'center', flexDirection: 'row' },
  heroPerkText: { color: tokens.colors.white, fontFamily: tokens.typography.bodyMedium, fontSize: 12, marginLeft: 5 },
  activeBanner: { alignItems: 'center', backgroundColor: tokens.colors.emeraldTint, borderRadius: 12, flexDirection: 'row', marginBottom: 22, padding: 12 },
  activeBannerText: { color: tokens.colors.availabilityGreen, flex: 1, fontFamily: tokens.typography.bodyMedium, fontSize: 12, marginLeft: 8 },
  sectionTitle: { color: tokens.colors.primaryText, fontFamily: tokens.typography.headingMedium, fontSize: 20, marginBottom: 12 },
  passCard: { marginBottom: 12, padding: 16 },
  passHeader: { alignItems: 'flex-start', flexDirection: 'row' },
  passIcon: { alignItems: 'center', borderRadius: 13, height: 44, justifyContent: 'center', width: 44 },
  passHeading: { flex: 1, marginLeft: 11, marginRight: 8 },
  passName: { color: tokens.colors.primaryText, fontFamily: tokens.typography.bodySemiBold, fontSize: 15 },
  passDescription: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 12, lineHeight: 17, marginTop: 4 },
  priceBlock: { alignItems: 'flex-end' },
  price: { color: tokens.colors.primaryText, fontFamily: tokens.typography.headingBold, fontSize: 20 },
  priceUnit: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 9, marginTop: 1 },
  spotBox: { alignItems: 'center', backgroundColor: tokens.colors.panelSurface, flexDirection: 'row', marginTop: 15, padding: 11 },
  spotCopy: { flex: 1, marginLeft: 8 },
  spotLabel: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 10 },
  spotName: { color: tokens.colors.primaryText, fontFamily: tokens.typography.bodyMedium, fontSize: 12, marginTop: 2 },
  schedule: { color: tokens.colors.municipalTeal, fontFamily: tokens.typography.bodyMedium, fontSize: 11, marginTop: 3 },
  perks: { marginTop: 14 },
  perk: { alignItems: 'center', flexDirection: 'row', marginBottom: 6 },
  perkText: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 12, marginLeft: 7 },
  actionButton: { alignItems: 'center', backgroundColor: tokens.colors.emerald, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', marginTop: 8, paddingVertical: 12 },
  actionButtonActive: { backgroundColor: tokens.colors.emeraldTint, borderColor: '#BDE5D0', borderWidth: 1 },
  actionText: { color: tokens.colors.white, fontFamily: tokens.typography.bodySemiBold, fontSize: 13, marginLeft: 7 },
  actionTextActive: { color: tokens.colors.availabilityGreen },
  note: { color: tokens.colors.secondaryText, fontFamily: tokens.typography.body, fontSize: 11, lineHeight: 16, marginHorizontal: 8, marginTop: 8, textAlign: 'center' },
});
