import { StyleSheet } from 'react-native';
import { tokens } from '../theme/tokens';

export const styles = StyleSheet.create({
  loading: { paddingTop: 60, alignItems: 'center' },
  statusCard: { padding: 22, alignItems: 'center' },
  statusIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  statusLabel: { fontFamily: tokens.typography.headingBold, fontSize: 20, marginTop: 12 },
  statusBlurb: { fontFamily: tokens.typography.body, fontSize: 13, color: tokens.colors.secondaryText, textAlign: 'center', marginTop: 6, lineHeight: 19 },
  suspensionText: { fontFamily: tokens.typography.bodyMedium, fontSize: 13, color: tokens.colors.warningAmber, marginTop: 8 },
  warningText: { fontFamily: tokens.typography.body, fontSize: 12, color: tokens.colors.secondaryText, marginTop: 4 },
  scoresRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
  scoreCard: { flex: 1, padding: 16, alignItems: 'center' },
  scoreValue: { fontFamily: tokens.typography.headingBold, fontSize: 26, color: tokens.colors.primaryText },
  scoreLabelRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  scoreLabel: { fontFamily: tokens.typography.bodyMedium, fontSize: 12, color: tokens.colors.primaryText, marginLeft: 5 },
  scoreMeta: { fontFamily: tokens.typography.body, fontSize: 11, color: tokens.colors.secondaryText, marginTop: 3 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 24, marginBottom: 10 },
  sectionTitle: { fontFamily: tokens.typography.headingMedium, fontSize: 18, color: tokens.colors.primaryText, marginBottom: 10 },
  sectionAction: { fontFamily: tokens.typography.bodyMedium, fontSize: 12, color: tokens.colors.municipalTeal },
  emptyCard: { padding: 20, alignItems: 'center', flexDirection: 'row', gap: 10 },
  emptyText: { fontFamily: tokens.typography.body, fontSize: 13, color: tokens.colors.secondaryText },
  noticeCard: { flexDirection: 'row', padding: 14, marginBottom: 10 },
  noticeDot: { width: 8, height: 8, borderRadius: 4, marginTop: 5, marginRight: 10 },
  noticeTitle: { fontFamily: tokens.typography.bodySemiBold, fontSize: 14, color: tokens.colors.primaryText },
  noticeBody: { fontFamily: tokens.typography.body, fontSize: 12, color: tokens.colors.secondaryText, marginTop: 3, lineHeight: 17 },
  noticeDate: { fontFamily: tokens.typography.body, fontSize: 10, color: '#9CA3AF', marginTop: 5 },
  actionRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 8 },
  actionTitle: { fontFamily: tokens.typography.bodySemiBold, fontSize: 13, color: tokens.colors.primaryText },
  actionReason: { fontFamily: tokens.typography.body, fontSize: 12, color: tokens.colors.secondaryText, marginTop: 2 },
  actionDate: { fontFamily: tokens.typography.body, fontSize: 10, color: '#9CA3AF', marginTop: 3 },
  appealCard: { padding: 16 },
  appealHelp: { fontFamily: tokens.typography.body, fontSize: 13, color: tokens.colors.secondaryText, lineHeight: 19 },
  appealInput: {
    marginTop: 12, minHeight: 90, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, padding: 12,
    fontFamily: tokens.typography.body, fontSize: 14, color: tokens.colors.primaryText, textAlignVertical: 'top',
  },
  appealButton: { marginTop: 12, backgroundColor: tokens.colors.emerald, borderRadius: 12, padding: 14, alignItems: 'center' },
  appealButtonText: { color: tokens.colors.white, fontFamily: tokens.typography.heading, fontSize: 15 },
  appealPending: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10 },
  appealPendingText: { fontFamily: tokens.typography.body, fontSize: 13, color: tokens.colors.secondaryText, flex: 1 },
});
